In [1]:
print('hello')

hello


In [2]:
a=34

In [3]:
type(a)

int

In [4]:
float(a)

34.0

In [5]:
for i in range(4,20,2):
    print('this is :',i)

this is : 4
this is : 6
this is : 8
this is : 10
this is : 12
this is : 14
this is : 16
this is : 18


In [6]:
if a<40:
    for i in range(1,10):
        print('hello',i)

hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
hello 7
hello 8
hello 9


In [7]:

import numpy as np

In [8]:
np.arange(1,33,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [9]:
a=np.arange(0,50).reshape(2,5,5)

In [10]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [11]:
a=np.array([2,3,4,5])

In [12]:
a


array([2, 3, 4, 5])

In [13]:
a**2

array([ 4,  9, 16, 25], dtype=int32)

In [14]:
a=np.array([[[2,3,4],[4,5,5]],[[3,4,5],[4,5,6]]])

In [15]:
a

array([[[2, 3, 4],
        [4, 5, 5]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [16]:
a.shape

(2, 2, 3)

In [17]:
a.size

12

In [18]:
a.dtype

dtype('int32')

In [20]:
pwd

'C:\\Users\\SA'

In [21]:
import pandas as pd

In [22]:
df=pd.read_csv('mtcars.csv')

In [23]:
df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [24]:

df[df['mpg']>20]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0        Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1    Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2       Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3   Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
7        Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8         Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
17        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
20   Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
26   Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

    carb  
0      4  
1      4  
2      1  
3      1  
7      2  
8      2  
17     1  
18     2  
19     1  
20     1  
25     1  
26     2  
27     2  
31     2

In [25]:

df.mpg.unique()

array([21. , 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 19.2, 17.8, 16.4, 17.3,
       15.2, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5, 13.3, 27.3, 26. ,
       15.8, 19.7, 15. ])

In [26]:
df.am.unique()

array([1, 0], dtype=int64)

In [27]:
df.isnull().sum(
)

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [28]:

df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [30]:

df.corr()

mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000

In [31]:
df.index

RangeIndex(start=0, stop=32, step=1)

In [32]:
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [33]:
df.iloc[0:3,0:3]

model   mpg  cyl
0      Mazda RX4  21.0    6
1  Mazda RX4 Wag  21.0    6
2     Datsun 710  22.8    4

In [34]:
df.iloc[29:32,0:3]

model   mpg  cyl
29   Ferrari Dino  19.7    6
30  Maserati Bora  15.0    8
31     Volvo 142E  21.4    4

In [35]:
df.loc[29:31,['model','mpg','cyl']]

model   mpg  cyl
29   Ferrari Dino  19.7    6
30  Maserati Bora  15.0    8
31     Volvo 142E  21.4    4

In [36]:
df.loc[df.am==1,'automatic']='yes'

In [37]:
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb automatic  
0      4     4       yes  
1      4     4       yes  
2      4     1       yes  
3      3     1       NaN  
4      3     2       NaN  
5      3     1       NaN  
6      3     4       NaN  
7      4     2       NaN  
8      4     2       NaN  
9      4     4       NaN  
10     4     4       NaN  
11     3     3       NaN  
12     3     3       NaN  
13     3     3       NaN  
14     3     4       NaN  
15     3     4       NaN  
16     3     4       NaN  
17     4     1       yes  
18     4     2       yes  
19     4     1       yes  
20     3     1       NaN  
21     3     2       NaN  
22     3     2       NaN  
23     3     4       NaN  
24     3     2       NaN  
25     4     1       yes  
26     5     2       yes  
27     5     2       yes  
28     5     4       yes  
29     5     6       yes  
30     5     8       yes  
31     4     2       yes

In [38]:
df.isnull().sum()

model         0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
automatic    19
dtype: int64

In [39]:
df.shape


(32, 13)

In [40]:
df.cyl.unique()

array([6, 4, 8], dtype=int64)

In [41]:
data=pd.read_csv('mtcarsmissing.csv')

In [42]:
data.head()

model   mpg  cyl   disp     hp  drat     wt   qsec   vs   am  \
0          Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0  1.0   
1      Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0  1.0   
2         Datsun 710  22.8  NaN    NaN    NaN   NaN    NaN    NaN  1.0  1.0   
3     Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0  NaN   
4  Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0  0.0   

   gear  carb  
0   4.0     4  
1   4.0     4  
2   4.0     1  
3   3.0     1  
4   3.0     2

In [43]:

df.isnull().sum(
)

model         0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
automatic    19
dtype: int64

In [44]:
data.isnull().sum()

model    0
mpg      0
cyl      3
disp     2
hp       2
drat     1
wt       2
qsec     2
vs       1
am       1
gear     1
carb     0
dtype: int64

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     29 non-null     float64
 3   disp    30 non-null     float64
 4   hp      30 non-null     float64
 5   drat    31 non-null     float64
 6   wt      30 non-null     float64
 7   qsec    30 non-null     float64
 8   vs      31 non-null     float64
 9   am      31 non-null     float64
 10  gear    31 non-null     float64
 11  carb    32 non-null     int64  
dtypes: float64(10), int64(1), object(1)
memory usage: 3.1+ KB


In [46]:
data.shape

(32, 12)

# fillna 
- we wil use to fill missing values

In [47]:
df.drop('automatic',axis=1,inplace=True)

In [48]:
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [49]:

data

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
2            Datsun 710  22.8  NaN    NaN    NaN   NaN    NaN    NaN  1.0   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
6            Duster 360  14.3  NaN  360.0  245.0  3.21  3.570  15.84  NaN   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440    NaN  1.0   
11           Merc 450SE  16.4  8.0  275.8    NaN  3.07  4.070  17.40  0.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
14   Cadillac Fleetwood  10.4  8.0    NaN  205.0  2.93  5.250  17.98  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
17             Fiat 128  32.4  NaN   78.7   66.0  4.08  2.200  19.47  1.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70    NaN  20.01  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
2   1.0   4.0     1  
3   NaN   3.0     1  
4   0.0   3.0     2  
5   0.0   3.0     1  
6   0.0   NaN     4  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
10  0.0   4.0     4  
11  0.0   3.0     3  
12  0.0   3.0     3  
13  0.0   3.0     3  
14  0.0   3.0     4  
15  0.0   3.0     4  
16  0.0   3.0     4  
17  1.0   4.0     1  
18  1.0   4.0     2  
19  1.0   4.0     1  
20  0.0   3.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [50]:

df.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [51]:
data.isnull().sum(
)

model    0
mpg      0
cyl      3
disp     2
hp       2
drat     1
wt       2
qsec     2
vs       1
am       1
gear     1
carb     0
dtype: int64

In [52]:

data.mean()

mpg      20.090625
cyl       6.275862
disp    226.770000
hp      147.366667
drat      3.588387
wt        3.272233
qsec     17.788333
vs        0.451613
am        0.419355
gear      3.709677
carb      2.812500
dtype: float64

In [53]:

data.fillna({
    'mpg':20,
    'cyl':6,
    'disp':226,
    'hp':147,
    'drat':3,
    'wt':3,
    'qsec':17,
    'vs':0.45,
    'am':0.41,
    'gear':3.7,
    'carb':2.8
})

model   mpg  cyl   disp     hp  drat     wt   qsec    vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.00   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.00   
2            Datsun 710  22.8  6.0  226.0  147.0  3.00  3.000  17.00  1.00   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.00   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.00   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.00   
6            Duster 360  14.3  6.0  360.0  245.0  3.21  3.570  15.84  0.45   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.00   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.00   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.00   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  17.00  1.00   
11           Merc 450SE  16.4  8.0  275.8  147.0  3.07  4.070  17.40  0.00   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.00   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.00   
14   Cadillac Fleetwood  10.4  8.0  226.0  205.0  2.93  5.250  17.98  0.00   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.00   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.00   
17             Fiat 128  32.4  6.0   78.7   66.0  4.08  2.200  19.47  1.00   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.00   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.00   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  3.000  20.01  1.00   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.00   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.00   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.00   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.00   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.00   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.00   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.00   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.00   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.00   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.00   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.00   

      am  gear  carb  
0   1.00   4.0     4  
1   1.00   4.0     4  
2   1.00   4.0     1  
3   0.41   3.0     1  
4   0.00   3.0     2  
5   0.00   3.0     1  
6   0.00   3.7     4  
7   0.00   4.0     2  
8   0.00   4.0     2  
9   0.00   4.0     4  
10  0.00   4.0     4  
11  0.00   3.0     3  
12  0.00   3.0     3  
13  0.00   3.0     3  
14  0.00   3.0     4  
15  0.00   3.0     4  
16  0.00   3.0     4  
17  1.00   4.0     1  
18  1.00   4.0     2  
19  1.00   4.0     1  
20  0.00   3.0     1  
21  0.00   3.0     2  
22  0.00   3.0     2  
23  0.00   3.0     4  
24  0.00   3.0     2  
25  1.00   4.0     1  
26  1.00   5.0     2  
27  1.00   5.0     2  
28  1.00   5.0     4  
29  1.00   5.0     6  
30  1.00   5.0     8  
31  1.00   4.0     2

In [62]:
data.fillna(data.mean())

model   mpg       cyl    disp          hp      drat  \
0             Mazda RX4  21.0  6.000000  160.00  110.000000  3.900000   
1         Mazda RX4 Wag  21.0  6.000000  160.00  110.000000  3.900000   
2            Datsun 710  22.8  6.275862  226.77  147.366667  3.588387   
3        Hornet 4 Drive  21.4  6.000000  258.00  110.000000  3.080000   
4     Hornet Sportabout  18.7  8.000000  360.00  175.000000  3.150000   
5               Valiant  18.1  6.000000  225.00  105.000000  2.760000   
6            Duster 360  14.3  6.275862  360.00  245.000000  3.210000   
7             Merc 240D  24.4  4.000000  146.70   62.000000  3.690000   
8              Merc 230  22.8  4.000000  140.80   95.000000  3.920000   
9              Merc 280  19.2  6.000000  167.60  123.000000  3.920000   
10            Merc 280C  17.8  6.000000  167.60  123.000000  3.920000   
11           Merc 450SE  16.4  8.000000  275.80  147.366667  3.070000   
12           Merc 450SL  17.3  8.000000  275.80  180.000000  3.070000   
13          Merc 450SLC  15.2  8.000000  275.80  180.000000  3.070000   
14   Cadillac Fleetwood  10.4  8.000000  226.77  205.000000  2.930000   
15  Lincoln Continental  10.4  8.000000  460.00  215.000000  3.000000   
16    Chrysler Imperial  14.7  8.000000  440.00  230.000000  3.230000   
17             Fiat 128  32.4  6.275862   78.70   66.000000  4.080000   
18          Honda Civic  30.4  4.000000   75.70   52.000000  4.930000   
19       Toyota Corolla  33.9  4.000000   71.10   65.000000  4.220000   
20        Toyota Corona  21.5  4.000000  120.10   97.000000  3.700000   
21     Dodge Challenger  15.5  8.000000  318.00  150.000000  2.760000   
22          AMC Javelin  15.2  8.000000  304.00  150.000000  3.150000   
23           Camaro Z28  13.3  8.000000  350.00  245.000000  3.730000   
24     Pontiac Firebird  19.2  8.000000  400.00  175.000000  3.080000   
25            Fiat X1-9  27.3  4.000000   79.00   66.000000  4.080000   
26        Porsche 914-2  26.0  4.000000  120.30   91.000000  4.430000   
27         Lotus Europa  30.4  4.000000   95.10  113.000000  3.770000   
28       Ford Pantera L  15.8  8.000000  351.00  264.000000  4.220000   
29         Ferrari Dino  19.7  6.000000  145.00  175.000000  3.620000   
30        Maserati Bora  15.0  8.000000  301.00  335.000000  3.540000   
31           Volvo 142E  21.4  4.000000  121.00  109.000000  4.110000   

          wt       qsec        vs        am      gear  carb  
0   2.620000  16.460000  0.000000  1.000000  4.000000     4  
1   2.875000  17.020000  0.000000  1.000000  4.000000     4  
2   3.272233  17.788333  1.000000  1.000000  4.000000     1  
3   3.215000  19.440000  1.000000  0.419355  3.000000     1  
4   3.440000  17.020000  0.000000  0.000000  3.000000     2  
5   3.460000  20.220000  1.000000  0.000000  3.000000     1  
6   3.570000  15.840000  0.451613  0.000000  3.709677     4  
7   3.190000  20.000000  1.000000  0.000000  4.000000     2  
8   3.150000  22.900000  1.000000  0.000000  4.000000     2  
9   3.440000  18.300000  1.000000  0.000000  4.000000     4  
10  3.440000  17.788333  1.000000  0.000000  4.000000     4  
11  4.070000  17.400000  0.000000  0.000000  3.000000     3  
12  3.730000  17.600000  0.000000  0.000000  3.000000     3  
13  3.780000  18.000000  0.000000  0.000000  3.000000     3  
14  5.250000  17.980000  0.000000  0.000000  3.000000     4  
15  5.424000  17.820000  0.000000  0.000000  3.000000     4  
16  5.345000  17.420000  0.000000  0.000000  3.000000     4  
17  2.200000  19.470000  1.000000  1.000000  4.000000     1  
18  1.615000  18.520000  1.000000  1.000000  4.000000     2  
19  1.835000  19.900000  1.000000  1.000000  4.000000     1  
20  3.272233  20.010000  1.000000  0.000000  3.000000     1  
21  3.520000  16.870000  0.000000  0.000000  3.000000     2  
22  3.435000  17.300000  0.000000  0.000000  3.000000     2  
23  3.840000  15.410000  0.000000  0.000000  3.000000     4  
24  3.845000  17.050000  0.000000  0.000000  3.000000     

In [54]:
data

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
2            Datsun 710  22.8  NaN    NaN    NaN   NaN    NaN    NaN  1.0   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
6            Duster 360  14.3  NaN  360.0  245.0  3.21  3.570  15.84  NaN   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440    NaN  1.0   
11           Merc 450SE  16.4  8.0  275.8    NaN  3.07  4.070  17.40  0.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
14   Cadillac Fleetwood  10.4  8.0    NaN  205.0  2.93  5.250  17.98  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
17             Fiat 128  32.4  NaN   78.7   66.0  4.08  2.200  19.47  1.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70    NaN  20.01  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
2   1.0   4.0     1  
3   NaN   3.0     1  
4   0.0   3.0     2  
5   0.0   3.0     1  
6   0.0   NaN     4  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
10  0.0   4.0     4  
11  0.0   3.0     3  
12  0.0   3.0     3  
13  0.0   3.0     3  
14  0.0   3.0     4  
15  0.0   3.0     4  
16  0.0   3.0     4  
17  1.0   4.0     1  
18  1.0   4.0     2  
19  1.0   4.0     1  
20  0.0   3.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [57]:

data.fillna(method='ffill')

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
2            Datsun 710  22.8  6.0  160.0  110.0  3.90  2.875  17.02  1.0   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
6            Duster 360  14.3  6.0  360.0  245.0  3.21  3.570  15.84  1.0   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
11           Merc 450SE  16.4  8.0  275.8  123.0  3.07  4.070  17.40  0.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
14   Cadillac Fleetwood  10.4  8.0  275.8  205.0  2.93  5.250  17.98  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
17             Fiat 128  32.4  8.0   78.7   66.0  4.08  2.200  19.47  1.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  1.835  20.01  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
2   1.0   4.0     1  
3   1.0   3.0     1  
4   0.0   3.0     2  
5   0.0   3.0     1  
6   0.0   3.0     4  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
10  0.0   4.0     4  
11  0.0   3.0     3  
12  0.0   3.0     3  
13  0.0   3.0     3  
14  0.0   3.0     4  
15  0.0   3.0     4  
16  0.0   3.0     4  
17  1.0   4.0     1  
18  1.0   4.0     2  
19  1.0   4.0     1  
20  0.0   3.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [58]:
data.fillna(method='bfill')

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
2            Datsun 710  22.8  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
6            Duster 360  14.3  4.0  360.0  245.0  3.21  3.570  15.84  1.0   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440  17.40  1.0   
11           Merc 450SE  16.4  8.0  275.8  180.0  3.07  4.070  17.40  0.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
14   Cadillac Fleetwood  10.4  8.0  460.0  205.0  2.93  5.250  17.98  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
17             Fiat 128  32.4  4.0   78.7   66.0  4.08  2.200  19.47  1.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70  3.520  20.01  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
2   1.0   4.0     1  
3   0.0   3.0     1  
4   0.0   3.0     2  
5   0.0   3.0     1  
6   0.0   4.0     4  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
10  0.0   4.0     4  
11  0.0   3.0     3  
12  0.0   3.0     3  
13  0.0   3.0     3  
14  0.0   3.0     4  
15  0.0   3.0     4  
16  0.0   3.0     4  
17  1.0   4.0     1  
18  1.0   4.0     2  
19  1.0   4.0     1  
20  0.0   3.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [59]:

data.head()

model   mpg  cyl   disp     hp  drat     wt   qsec   vs   am  \
0          Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0  1.0   
1      Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0  1.0   
2         Datsun 710  22.8  NaN    NaN    NaN   NaN    NaN    NaN  1.0  1.0   
3     Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0  NaN   
4  Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0  0.0   

   gear  carb  
0   4.0     4  
1   4.0     4  
2   4.0     1  
3   3.0     1  
4   3.0     2

In [60]:

data.dropna()

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
4   0.0   3.0     2  
5   0.0   3.0     1  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
12  0.0   3.0     3  
13  0.0   3.0     3  
15  0.0   3.0     4  
16  0.0   3.0     4  
18  1.0   4.0     2  
19  1.0   4.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [61]:
data.fillna(df.mean())

model   mpg     cyl        disp        hp      drat  \
0             Mazda RX4  21.0  6.0000  160.000000  110.0000  3.900000   
1         Mazda RX4 Wag  21.0  6.0000  160.000000  110.0000  3.900000   
2            Datsun 710  22.8  6.1875  230.721875  146.6875  3.596563   
3        Hornet 4 Drive  21.4  6.0000  258.000000  110.0000  3.080000   
4     Hornet Sportabout  18.7  8.0000  360.000000  175.0000  3.150000   
5               Valiant  18.1  6.0000  225.000000  105.0000  2.760000   
6            Duster 360  14.3  6.1875  360.000000  245.0000  3.210000   
7             Merc 240D  24.4  4.0000  146.700000   62.0000  3.690000   
8              Merc 230  22.8  4.0000  140.800000   95.0000  3.920000   
9              Merc 280  19.2  6.0000  167.600000  123.0000  3.920000   
10            Merc 280C  17.8  6.0000  167.600000  123.0000  3.920000   
11           Merc 450SE  16.4  8.0000  275.800000  146.6875  3.070000   
12           Merc 450SL  17.3  8.0000  275.800000  180.0000  3.070000   
13          Merc 450SLC  15.2  8.0000  275.800000  180.0000  3.070000   
14   Cadillac Fleetwood  10.4  8.0000  230.721875  205.0000  2.930000   
15  Lincoln Continental  10.4  8.0000  460.000000  215.0000  3.000000   
16    Chrysler Imperial  14.7  8.0000  440.000000  230.0000  3.230000   
17             Fiat 128  32.4  6.1875   78.700000   66.0000  4.080000   
18          Honda Civic  30.4  4.0000   75.700000   52.0000  4.930000   
19       Toyota Corolla  33.9  4.0000   71.100000   65.0000  4.220000   
20        Toyota Corona  21.5  4.0000  120.100000   97.0000  3.700000   
21     Dodge Challenger  15.5  8.0000  318.000000  150.0000  2.760000   
22          AMC Javelin  15.2  8.0000  304.000000  150.0000  3.150000   
23           Camaro Z28  13.3  8.0000  350.000000  245.0000  3.730000   
24     Pontiac Firebird  19.2  8.0000  400.000000  175.0000  3.080000   
25            Fiat X1-9  27.3  4.0000   79.000000   66.0000  4.080000   
26        Porsche 914-2  26.0  4.0000  120.300000   91.0000  4.430000   
27         Lotus Europa  30.4  4.0000   95.100000  113.0000  3.770000   
28       Ford Pantera L  15.8  8.0000  351.000000  264.0000  4.220000   
29         Ferrari Dino  19.7  6.0000  145.000000  175.0000  3.620000   
30        Maserati Bora  15.0  8.0000  301.000000  335.0000  3.540000   
31           Volvo 142E  21.4  4.0000  121.000000  109.0000  4.110000   

         wt      qsec      vs       am    gear  carb  
0   2.62000  16.46000  0.0000  1.00000  4.0000     4  
1   2.87500  17.02000  0.0000  1.00000  4.0000     4  
2   3.21725  17.84875  1.0000  1.00000  4.0000     1  
3   3.21500  19.44000  1.0000  0.40625  3.0000     1  
4   3.44000  17.02000  0.0000  0.00000  3.0000     2  
5   3.46000  20.22000  1.0000  0.00000  3.0000     1  
6   3.57000  15.84000  0.4375  0.00000  3.6875     4  
7   3.19000  20.00000  1.0000  0.00000  4.0000     2  
8   3.15000  22.90000  1.0000  0.00000  4.0000     2  
9   3.44000  18.30000  1.0000  0.00000  4.0000     4  
10  3.44000  17.84875  1.0000  0.00000  4.0000     4  
11  4.07000  17.40000  0.0000  0.00000  3.0000     3  
12  3.73000  17.60000  0.0000  0.00000  3.0000     3  
13  3.78000  18.00000  0.0000  0.00000  3.0000     3  
14  5.25000  17.98000  0.0000  0.00000  3.0000     4  
15  5.42400  17.82000  0.0000  0.00000  3.0000     4  
16  5.34500  17.42000  0.0000  0.00000  3.0000     4  
17  2.20000  19.47000  1.0000  1.00000  4.0000     1  
18  1.61500  18.52000  1.0000  1.00000  4.0000     2  
19  1.83500  19.90000  1.0000  1.00000  4.0000     1  
20  3.21725  20.01000  1.0000  0.00000  3.0000     1  
21  3.52000  16.87000  0.0000  0.00000  3.0000     2  
22  3.43500  17.30000  0.0000  0.00000  3.0000     2  
23  3.84000  15.41000  0.0000  0.00000  3.0000     4  
24  3.84500  17.05000  0.0000  0.00000  3.0000     2  
25  1.93500  18.90000  1.0000  1.00000  4.0000     1  
26  2.14000  16.70000  0.0000  1.00000  5.0000     2  
27  1.51300  16.90000  1.0000  1.00000  5.0000     2  
28  3.17000  

In [63]:
data

model   mpg  cyl   disp     hp  drat     wt   qsec   vs  \
0             Mazda RX4  21.0  6.0  160.0  110.0  3.90  2.620  16.46  0.0   
1         Mazda RX4 Wag  21.0  6.0  160.0  110.0  3.90  2.875  17.02  0.0   
2            Datsun 710  22.8  NaN    NaN    NaN   NaN    NaN    NaN  1.0   
3        Hornet 4 Drive  21.4  6.0  258.0  110.0  3.08  3.215  19.44  1.0   
4     Hornet Sportabout  18.7  8.0  360.0  175.0  3.15  3.440  17.02  0.0   
5               Valiant  18.1  6.0  225.0  105.0  2.76  3.460  20.22  1.0   
6            Duster 360  14.3  NaN  360.0  245.0  3.21  3.570  15.84  NaN   
7             Merc 240D  24.4  4.0  146.7   62.0  3.69  3.190  20.00  1.0   
8              Merc 230  22.8  4.0  140.8   95.0  3.92  3.150  22.90  1.0   
9              Merc 280  19.2  6.0  167.6  123.0  3.92  3.440  18.30  1.0   
10            Merc 280C  17.8  6.0  167.6  123.0  3.92  3.440    NaN  1.0   
11           Merc 450SE  16.4  8.0  275.8    NaN  3.07  4.070  17.40  0.0   
12           Merc 450SL  17.3  8.0  275.8  180.0  3.07  3.730  17.60  0.0   
13          Merc 450SLC  15.2  8.0  275.8  180.0  3.07  3.780  18.00  0.0   
14   Cadillac Fleetwood  10.4  8.0    NaN  205.0  2.93  5.250  17.98  0.0   
15  Lincoln Continental  10.4  8.0  460.0  215.0  3.00  5.424  17.82  0.0   
16    Chrysler Imperial  14.7  8.0  440.0  230.0  3.23  5.345  17.42  0.0   
17             Fiat 128  32.4  NaN   78.7   66.0  4.08  2.200  19.47  1.0   
18          Honda Civic  30.4  4.0   75.7   52.0  4.93  1.615  18.52  1.0   
19       Toyota Corolla  33.9  4.0   71.1   65.0  4.22  1.835  19.90  1.0   
20        Toyota Corona  21.5  4.0  120.1   97.0  3.70    NaN  20.01  1.0   
21     Dodge Challenger  15.5  8.0  318.0  150.0  2.76  3.520  16.87  0.0   
22          AMC Javelin  15.2  8.0  304.0  150.0  3.15  3.435  17.30  0.0   
23           Camaro Z28  13.3  8.0  350.0  245.0  3.73  3.840  15.41  0.0   
24     Pontiac Firebird  19.2  8.0  400.0  175.0  3.08  3.845  17.05  0.0   
25            Fiat X1-9  27.3  4.0   79.0   66.0  4.08  1.935  18.90  1.0   
26        Porsche 914-2  26.0  4.0  120.3   91.0  4.43  2.140  16.70  0.0   
27         Lotus Europa  30.4  4.0   95.1  113.0  3.77  1.513  16.90  1.0   
28       Ford Pantera L  15.8  8.0  351.0  264.0  4.22  3.170  14.50  0.0   
29         Ferrari Dino  19.7  6.0  145.0  175.0  3.62  2.770  15.50  0.0   
30        Maserati Bora  15.0  8.0  301.0  335.0  3.54  3.570  14.60  0.0   
31           Volvo 142E  21.4  4.0  121.0  109.0  4.11  2.780  18.60  1.0   

     am  gear  carb  
0   1.0   4.0     4  
1   1.0   4.0     4  
2   1.0   4.0     1  
3   NaN   3.0     1  
4   0.0   3.0     2  
5   0.0   3.0     1  
6   0.0   NaN     4  
7   0.0   4.0     2  
8   0.0   4.0     2  
9   0.0   4.0     4  
10  0.0   4.0     4  
11  0.0   3.0     3  
12  0.0   3.0     3  
13  0.0   3.0     3  
14  0.0   3.0     4  
15  0.0   3.0     4  
16  0.0   3.0     4  
17  1.0   4.0     1  
18  1.0   4.0     2  
19  1.0   4.0     1  
20  0.0   3.0     1  
21  0.0   3.0     2  
22  0.0   3.0     2  
23  0.0   3.0     4  
24  0.0   3.0     2  
25  1.0   4.0     1  
26  1.0   5.0     2  
27  1.0   5.0     2  
28  1.0   5.0     4  
29  1.0   5.0     6  
30  1.0   5.0     8  
31  1.0   4.0     2

In [64]:

data.fillna(data.mean(),inplace=True)

In [65]:
data

model   mpg       cyl    disp          hp      drat  \
0             Mazda RX4  21.0  6.000000  160.00  110.000000  3.900000   
1         Mazda RX4 Wag  21.0  6.000000  160.00  110.000000  3.900000   
2            Datsun 710  22.8  6.275862  226.77  147.366667  3.588387   
3        Hornet 4 Drive  21.4  6.000000  258.00  110.000000  3.080000   
4     Hornet Sportabout  18.7  8.000000  360.00  175.000000  3.150000   
5               Valiant  18.1  6.000000  225.00  105.000000  2.760000   
6            Duster 360  14.3  6.275862  360.00  245.000000  3.210000   
7             Merc 240D  24.4  4.000000  146.70   62.000000  3.690000   
8              Merc 230  22.8  4.000000  140.80   95.000000  3.920000   
9              Merc 280  19.2  6.000000  167.60  123.000000  3.920000   
10            Merc 280C  17.8  6.000000  167.60  123.000000  3.920000   
11           Merc 450SE  16.4  8.000000  275.80  147.366667  3.070000   
12           Merc 450SL  17.3  8.000000  275.80  180.000000  3.070000   
13          Merc 450SLC  15.2  8.000000  275.80  180.000000  3.070000   
14   Cadillac Fleetwood  10.4  8.000000  226.77  205.000000  2.930000   
15  Lincoln Continental  10.4  8.000000  460.00  215.000000  3.000000   
16    Chrysler Imperial  14.7  8.000000  440.00  230.000000  3.230000   
17             Fiat 128  32.4  6.275862   78.70   66.000000  4.080000   
18          Honda Civic  30.4  4.000000   75.70   52.000000  4.930000   
19       Toyota Corolla  33.9  4.000000   71.10   65.000000  4.220000   
20        Toyota Corona  21.5  4.000000  120.10   97.000000  3.700000   
21     Dodge Challenger  15.5  8.000000  318.00  150.000000  2.760000   
22          AMC Javelin  15.2  8.000000  304.00  150.000000  3.150000   
23           Camaro Z28  13.3  8.000000  350.00  245.000000  3.730000   
24     Pontiac Firebird  19.2  8.000000  400.00  175.000000  3.080000   
25            Fiat X1-9  27.3  4.000000   79.00   66.000000  4.080000   
26        Porsche 914-2  26.0  4.000000  120.30   91.000000  4.430000   
27         Lotus Europa  30.4  4.000000   95.10  113.000000  3.770000   
28       Ford Pantera L  15.8  8.000000  351.00  264.000000  4.220000   
29         Ferrari Dino  19.7  6.000000  145.00  175.000000  3.620000   
30        Maserati Bora  15.0  8.000000  301.00  335.000000  3.540000   
31           Volvo 142E  21.4  4.000000  121.00  109.000000  4.110000   

          wt       qsec        vs        am      gear  carb  
0   2.620000  16.460000  0.000000  1.000000  4.000000     4  
1   2.875000  17.020000  0.000000  1.000000  4.000000     4  
2   3.272233  17.788333  1.000000  1.000000  4.000000     1  
3   3.215000  19.440000  1.000000  0.419355  3.000000     1  
4   3.440000  17.020000  0.000000  0.000000  3.000000     2  
5   3.460000  20.220000  1.000000  0.000000  3.000000     1  
6   3.570000  15.840000  0.451613  0.000000  3.709677     4  
7   3.190000  20.000000  1.000000  0.000000  4.000000     2  
8   3.150000  22.900000  1.000000  0.000000  4.000000     2  
9   3.440000  18.300000  1.000000  0.000000  4.000000     4  
10  3.440000  17.788333  1.000000  0.000000  4.000000     4  
11  4.070000  17.400000  0.000000  0.000000  3.000000     3  
12  3.730000  17.600000  0.000000  0.000000  3.000000     3  
13  3.780000  18.000000  0.000000  0.000000  3.000000     3  
14  5.250000  17.980000  0.000000  0.000000  3.000000     4  
15  5.424000  17.820000  0.000000  0.000000  3.000000     4  
16  5.345000  17.420000  0.000000  0.000000  3.000000     4  
17  2.200000  19.470000  1.000000  1.000000  4.000000     1  
18  1.615000  18.520000  1.000000  1.000000  4.000000     2  
19  1.835000  19.900000  1.000000  1.000000  4.000000     1  
20  3.272233  20.010000  1.000000  0.000000  3.000000     1  
21  3.520000  16.870000  0.000000  0.000000  3.000000     2  
22  3.435000  17.300000  0.000000  0.000000  3.000000     2  
23  3.840000  15.410000  0.000000  0.000000  3.000000     4  
24  3.845000  17.050000  0.000000  0.000000  3.000000     

In [66]:

data.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

# pandas merge and groupby

In [70]:
 df1=pd.DataFrame({
     'name':['farooq','asma','anick','abdali'],
     'maths':[67,88,98,76]
 })

In [71]:
df1

name  maths
0  farooq     67
1    asma     88
2   anick     98
3  abdali     76

In [72]:
 df2=pd.DataFrame({
     'name':['farooq','farah','anick','abdali'],
     'maths':[67,90,98,76]
 })

In [74]:
pd.merge(df1,df2,on='name')

name  maths_x  maths_y
0  farooq       67       67
1   anick       98       98
2  abdali       76       76

In [75]:
pd.merge(df1,df2,on='name',how='left')

name  maths_x  maths_y
0  farooq       67     67.0
1    asma       88      NaN
2   anick       98     98.0
3  abdali       76     76.0

In [79]:
pd.merge(df1,df2,on='name',how='right')

name  maths_x  maths_y
0  farooq     67.0       67
1   farah      NaN       90
2   anick     98.0       98
3  abdali     76.0       76

In [82]:

pd.merge(df1,df2,on='name',how='outer')


name  maths_x  maths_y
0  farooq     67.0     67.0
1    asma     88.0      NaN
2   anick     98.0     98.0
3  abdali     76.0     76.0
4   farah      NaN     90.0

In [83]:
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [84]:

df.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [88]:
cyl_group=df.groupby('cyl')

In [90]:
cyl_group.mean()

mpg        disp          hp      drat        wt       qsec  \
cyl                                                                     
4    26.663636  105.136364   82.636364  4.070909  2.285727  19.137273   
6    19.742857  183.314286  122.285714  3.585714  3.117143  17.977143   
8    15.100000  353.100000  209.214286  3.229286  3.999214  16.772143   

           vs        am      gear      carb  
cyl                                          
4    0.909091  0.727273  4.090909  1.545455  
6    0.571429  0.428571  3.857143  3.428571  
8    0.000000  0.142857  3.285714  3.500000

In [98]:
am_gr=df.groupby('am')

In [99]:
am_gr

In [100]:
am_gr.mean()

mpg       cyl        disp          hp      drat        wt  \
am                                                                    
0   17.147368  6.947368  290.378947  160.263158  3.286316  3.768895   
1   24.392308  5.076923  143.530769  126.846154  4.050000  2.411000   

         qsec        vs      gear      carb  
am                                           
0   18.183158  0.368421  3.210526  2.736842  
1   17.360000  0.538462  4.384615  2.923077

In [101]:
import numpy as np

In [106]:
np.random.rand()

0.8490787310277219

In [118]:
np.random.randint(2,100,2)

array([77, 45])

In [133]:
np.random.randint(0,100,100).reshape(10,10)

array([[93, 41,  3, 50, 82, 94, 78, 68, 13, 29],
       [44, 13, 28, 18,  6, 21, 64, 33, 58,  7],
       [58, 51, 83, 49, 18, 30, 45, 22, 89, 94],
       [61, 72, 68, 36, 79, 41, 12, 73,  3, 35],
       [49, 84, 76,  4, 98, 54, 30, 53, 94, 89],
       [31,  0, 34, 12, 31, 73, 53, 56, 38, 42],
       [43, 55, 87, 96, 67, 39, 15, 67, 92, 78],
       [40, 94, 89,  1, 12, 29, 74, 75, 45, 70],
       [34, 41, 59,  8, 56, 55, 79, 43, 87, 11],
       [51, 24, 32, 55, 54, 22, 16, 19, 54, 76]])

In [152]:
arr=np.random.randint(0,20,25).reshape(5,5)

In [159]:
arr

array([[10,  3, 19, 12,  0],
       [ 6, 17, 15,  6, 19],
       [ 8, 11,  5,  7, 11],
       [ 6, 16, 17, 12, 12],
       [10,  3,  0, 10, 13]])

In [161]:
arr1=np.arange(25).reshape(5,5)

In [162]:

arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [164]:
np.vstack((arr,arr1))

array([[10,  3, 19, 12,  0],
       [ 6, 17, 15,  6, 19],
       [ 8, 11,  5,  7, 11],
       [ 6, 16, 17, 12, 12],
       [10,  3,  0, 10, 13],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [165]:
np.hstack((arr,arr1))

array([[10,  3, 19, 12,  0,  0,  1,  2,  3,  4],
       [ 6, 17, 15,  6, 19,  5,  6,  7,  8,  9],
       [ 8, 11,  5,  7, 11, 10, 11, 12, 13, 14],
       [ 6, 16, 17, 12, 12, 15, 16, 17, 18, 19],
       [10,  3,  0, 10, 13, 20, 21, 22, 23, 24]])

In [166]:
arr2=np.hstack((arr,arr1))

In [167]:
arr2

array([[10,  3, 19, 12,  0,  0,  1,  2,  3,  4],
       [ 6, 17, 15,  6, 19,  5,  6,  7,  8,  9],
       [ 8, 11,  5,  7, 11, 10, 11, 12, 13, 14],
       [ 6, 16, 17, 12, 12, 15, 16, 17, 18, 19],
       [10,  3,  0, 10, 13, 20, 21, 22, 23, 24]])

In [169]:
arr3=np.vstack((arr2,arr2))

In [170]:
arr3

array([[10,  3, 19, 12,  0,  0,  1,  2,  3,  4],
       [ 6, 17, 15,  6, 19,  5,  6,  7,  8,  9],
       [ 8, 11,  5,  7, 11, 10, 11, 12, 13, 14],
       [ 6, 16, 17, 12, 12, 15, 16, 17, 18, 19],
       [10,  3,  0, 10, 13, 20, 21, 22, 23, 24],
       [10,  3, 19, 12,  0,  0,  1,  2,  3,  4],
       [ 6, 17, 15,  6, 19,  5,  6,  7,  8,  9],
       [ 8, 11,  5,  7, 11, 10, 11, 12, 13, 14],
       [ 6, 16, 17, 12, 12, 15, 16, 17, 18, 19],
       [10,  3,  0, 10, 13, 20, 21, 22, 23, 24]])

In [173]:
np.hsplit(arr3,5)

[array([[10,  3],
        [ 6, 17],
        [ 8, 11],
        [ 6, 16],
        [10,  3],
        [10,  3],
        [ 6, 17],
        [ 8, 11],
        [ 6, 16],
        [10,  3]]),
 array([[19, 12],
        [15,  6],
        [ 5,  7],
        [17, 12],
        [ 0, 10],
        [19, 12],
        [15,  6],
        [ 5,  7],
        [17, 12],
        [ 0, 10]]),
 array([[ 0,  0],
        [19,  5],
        [11, 10],
        [12, 15],
        [13, 20],
        [ 0,  0],
        [19,  5],
        [11, 10],
        [12, 15],
        [13, 20]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22],
        [ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]