NumPy - Numeric Python

In [36]:
import numpy as np

In [37]:
x = np.array([5,4,3,4,5,7,8,5,4,3])

In [7]:
x

array([5, 4, 3, 4, 5, 7, 8, 5, 4, 3])

- homogenious datatype

In [8]:
arr2 = np.array([5,4,3,4.2,5,7,8,5,4,3])

In [9]:
arr2

array([5. , 4. , 3. , 4.2, 5. , 7. , 8. , 5. , 4. , 3. ])

In [10]:
arr3 = np.array([4, 3, 5, 4, 6, 3.14, 'suhail'])
arr3

array(['4', '3', '5', '4', '6', '3.14', 'suhail'], dtype='<U32')

In [11]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 0.0])
arr4

array([1., 2., 3., 4., 5., 6., 0.])

In [12]:
arr4.dtype

dtype('float64')

In [13]:
arr5= np.array([4,5,3,3,4,5,6])
arr5

array([4, 5, 3, 3, 4, 5, 6])

In [14]:
arr5.dtype

dtype('int32')

In [15]:
arr5.size

7

In [16]:
arr2

array([5. , 4. , 3. , 4.2, 5. , 7. , 8. , 5. , 4. , 3. ])

In [17]:
print (arr2.dtype)
print (arr2.size)

float64
10


In [23]:
arr5 = np.arange(0, 10000)

In [24]:
arr5

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [25]:
arr5.size

10000

In [26]:
arr5 * 2

array([    0,     2,     4, ..., 19994, 19996, 19998])

In [27]:
arr6 = np.arange(10, 51)

In [28]:
arr6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Numpy arrays can be multi-dimentional

In [29]:
arr7 = np.array([1,2,3,4,5,6,7,8])
arr7

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr7.ndim

1

In [38]:
arr8 = np.array([[1,2,3],[4,5,6]])
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
print(arr8.ndim)
print (arr8.dtype)
print (arr8.size)

2
int32
6


In [32]:
arr9 = np.array([ [ [1,2], [3,4] ], [[5,6], [7,8] ]  ])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
arr9.ndim

3

In [35]:
arr7=np.array([1,2,3,4,5,6,7])
arr7.ndim

1

In [47]:
arr8 = np.array([  [1,2,1], [2,1,2], [3,3,3]  ])

In [48]:
arr8

array([[1, 2, 1],
       [2, 1, 2],
       [3, 3, 3]])

In [49]:
arr8.ndim

2

In [50]:
arr9 = np.array([[[1,2,3],[4,5,0]],[[1,2,3],[4,4,4]]])
arr9

array([[[1, 2, 3],
        [4, 5, 0]],

       [[1, 2, 3],
        [4, 4, 4]]])

In [53]:
print (arr9.shape)
print (arr9.size)
print (arr9.dtype)
print (arr9.ndim)

(2, 2, 3)
12
int32
3


In [54]:
arr10 = np.arange(10).reshape(2,5)

In [55]:
arr10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
print (arr10.shape)
print (arr10.size)
print (arr10.ndim)
print (arr10.dtype)

(2, 5)
10
2
int32


In [59]:
arr10 = np.array([[[1,2,3],[4,4,4]], [[1,1,1], [1,2,4]]])

In [60]:
arr10

array([[[1, 2, 3],
        [4, 4, 4]],

       [[1, 1, 1],
        [1, 2, 4]]])

In [66]:
arr11 = np.arange(100)
arr11 = arr11.reshape(2,10,5)
arr11

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [67]:
print (arr11.shape, arr11.size, arr11.ndim)

(2, 10, 5) 100 3


In [72]:
arr11 = np.arange(10).reshape(2,5)

arr11

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
arr11.shape

(2, 5)

In [81]:
arr12 = np.arange(100).reshape(2,50)
arr12

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [87]:
arr13 = np.arange(50).reshape(1,1,1,1,5,10)
arr13

array([[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
           [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
           [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
           [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]]]]])

In [88]:
arr13.shape

(1, 1, 1, 1, 5, 10)

In [89]:
arr13.ndim

6

In [90]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### create a numpy array with the shape of 15, 10 containing of all 0's

In [100]:
arr14 = np.zeros(150).reshape(15,10).astype('int')
print (arr14.dtype)
arr14

int32


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [102]:
arr14.ravel()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])