In [1]:
import numpy as np

In [2]:
arr1 = np.arange(100)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
arr1.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# generate random number between 0 and 1

In [9]:
np.random.rand()

0.18566351871652698

In [27]:
np.random.randint(900, 1000, 100)

array([978, 902, 964, 999, 971, 907, 953, 937, 951, 950, 986, 999, 953,
       943, 921, 981, 948, 986, 906, 996, 972, 968, 974, 955, 910, 931,
       984, 941, 973, 903, 968, 932, 969, 983, 987, 909, 980, 913, 973,
       914, 947, 951, 971, 995, 978, 907, 946, 920, 987, 978, 929, 986,
       902, 987, 998, 994, 967, 936, 912, 930, 985, 905, 906, 982, 918,
       907, 936, 945, 988, 927, 991, 906, 925, 936, 931, 902, 909, 905,
       990, 967, 902, 997, 989, 906, 951, 982, 950, 957, 956, 992, 994,
       903, 963, 985, 930, 902, 983, 900, 917, 915])

In [29]:
np.random.randint(0,100, 100).reshape(10,10)

array([[54, 46, 77, 14, 98, 58, 28, 14, 97, 20],
       [36, 16,  3, 59, 45, 57, 56, 82, 69, 62],
       [10, 21, 55, 61, 51, 59, 81, 69,  1, 76],
       [ 5, 72, 33, 51, 44, 96, 53, 67, 95, 88],
       [56, 77, 41, 20, 12, 70, 51, 77, 89, 42],
       [77,  3, 34, 56, 93, 50, 70, 19, 66, 17],
       [69, 20,  0, 28, 12, 28, 36, 64, 85, 44],
       [14, 61, 58, 71, 71, 22, 51, 73, 62, 84],
       [54,  1, 71, 10, 77,  1, 89,  3, 26, 17],
       [60, 65, 73, 26, 55, 44, 79, 69, 27, 36]])

# generate a random integer array of shape 5x5 with values inbetween 0 and 20

In [35]:
np.random.randint(0,20,25).reshape(5,5)

array([[15, 14,  0, 18, 18],
       [19,  0,  0,  5,  8],
       [11,  5,  2, 14, 19],
       [ 8,  6, 17,  0,  6],
       [ 9,  0,  6,  7, 16]])

# stacking

In [36]:
arr3 = np.random.randint(0,20,25).reshape(5,5)
arr3

array([[ 4, 13, 16, 14, 17],
       [ 3,  8, 17,  1, 13],
       [14, 13, 11, 19, 16],
       [18,  7, 18,  2, 14],
       [ 3, 12, 15,  7,  4]])

In [38]:
arr4 = np.arange(25).reshape(5,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
np.vstack((arr3,arr4))

array([[ 4, 13, 16, 14, 17],
       [ 3,  8, 17,  1, 13],
       [14, 13, 11, 19, 16],
       [18,  7, 18,  2, 14],
       [ 3, 12, 15,  7,  4],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
np.hstack((arr3, arr4))

array([[ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
       [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
       [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
       [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
       [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24]])

# split

In [42]:
arr5 = np.hstack((arr3, arr4))
arr5

array([[ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
       [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
       [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
       [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
       [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24]])

In [48]:
arr6 = np.vstack((arr5, arr5))
arr6

array([[ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
       [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
       [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
       [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
       [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24],
       [ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
       [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
       [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
       [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
       [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24]])

In [53]:
np.hsplit(arr6, 2)

[array([[ 4, 13, 16, 14, 17],
        [ 3,  8, 17,  1, 13],
        [14, 13, 11, 19, 16],
        [18,  7, 18,  2, 14],
        [ 3, 12, 15,  7,  4],
        [ 4, 13, 16, 14, 17],
        [ 3,  8, 17,  1, 13],
        [14, 13, 11, 19, 16],
        [18,  7, 18,  2, 14],
        [ 3, 12, 15,  7,  4]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [57]:
np.vsplit(arr6, 2)

[array([[ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
        [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
        [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
        [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
        [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24]]),
 array([[ 4, 13, 16, 14, 17,  0,  1,  2,  3,  4],
        [ 3,  8, 17,  1, 13,  5,  6,  7,  8,  9],
        [14, 13, 11, 19, 16, 10, 11, 12, 13, 14],
        [18,  7, 18,  2, 14, 15, 16, 17, 18, 19],
        [ 3, 12, 15,  7,  4, 20, 21, 22, 23, 24]])]