In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import sklearn.datasets 
from sklearn.model_selection import train_test_split
from scipy import stats
from scipy.optimize import minimize

In [71]:
wine=sklearn.datasets.load_wine()

In [72]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [73]:
x,y=wine.data,wine.target

In [74]:
x.shape,y.shape

((178, 13), (178,))

In [75]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=2600)
lr.fit(x,y)

LogisticRegression(max_iter=2600)

In [76]:
lr.score(x,y)

0.9943820224719101

In [77]:
lr.predict_proba(x[:1])

array([[9.99806754e-01, 2.66795552e-05, 1.66566711e-04]])

In [79]:
lr.coef_@x[2]+lr.intercept_

array([ 6.89450561, -4.147961  , -2.74654461])

In [80]:
x[2]

array([1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
       3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
       1.185e+03])

# linear svc
- it work same as logistic regresssion
- note it works on more than two classes

In [86]:
from sklearn.svm import LinearSVC
svm=LinearSVC()
svm.fit(x,y)

C:\Users\SA\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [87]:
svm.score(x,y)

0.7921348314606742

In [88]:
from scipy.optimize import minimize

In [89]:
minimize(np.square,0).x

array([0.])

In [90]:
minimize(np.square,2).x

array([-1.88846401e-08])

# non linear svc

In [83]:
from sklearn.svm import SVC

In [84]:
svm=SVC()
svm.fit(x,y)

SVC()

In [85]:
svm.score(x,y)

0.7078651685393258

# underfitting
- if model is too simple it will not be able to learn data  very well so,low training accuracy
# overfitting
- if model is too complex it  will learn data  so,low testing accuracy

In [55]:
from sklearn import datasets

In [56]:
digits=datasets.load_digits()

In [58]:
type(digits)

sklearn.utils.Bunch

In [61]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target)

# train multiple model

In [62]:
x=np.arange(3)

In [63]:
x

array([0, 1, 2])

In [64]:
y=np.arange(3,6)

In [65]:
y

array([3, 4, 5])

In [66]:
x*y

array([ 0,  4, 10])

In [67]:
x@y

14

In [68]:
np.sum(x*y)

14

# linear classifer

## raw model output=coeffiecients.features + intercept