In [3]:
a='farooq'
print('my name is :',a,'khan')

my name is : farooq khan


In [4]:
2**4

16

In [5]:
15/3

5.0

In [6]:
15//3

5

In [7]:
weight=65
height=1.5
bmi=weight/height**2
print('body mass is :',bmi)

body mass is : 28.88888888888889


In [13]:
 age=15
    
if age<=15:
        print('candidate is shortlisted')

else:
        print("don't select")

candidate is shortlisted


In [19]:
check_petrol=int(input())
if check_petrol<5:
    print('refill the oil')
else:
    print("don't need")

4
refill the oil


In [24]:
for i in range(0,10,2):
  
    print(i,'hello world')

0 hello world
2 hello world
4 hello world
6 hello world
8 hello world


In [26]:
for i in range(0,100):
    if i%4==0:
        print(i)

0
4
8
12
16
20
24
28
32
36
40
44
48
52
56
60
64
68
72
76
80
84
88
92
96


In [29]:
sum=0
for i in range(0,101):
    sum=sum+i
print(sum)

5050


In [34]:
def show(a,b):
   sum=a+b
   return sum

In [36]:
print(show(2,3))

5


In [37]:
show(5,5)

10

In [46]:
def user(user,password):
    
     if user=='suhail' and password=='hello':
            return True
     else:
            return False

In [47]:
if user('suhai','hello')==True:
    print('give access')
else:
    print('authentication problem')

authentication problem


In [48]:
list1=[90,80,70,60]

In [49]:
list1

[90, 80, 70, 60]

In [50]:
list1.append(10)

In [51]:
list1

[90, 80, 70, 60, 10]

In [52]:
list1.extend([2,3,4])

In [53]:
list1

[90, 80, 70, 60, 10, 2, 3, 4]

In [54]:
list1.pop()

4

In [55]:
list1

[90, 80, 70, 60, 10, 2, 3]

In [57]:
list1.insert(0,2)

In [58]:
list1

[2, 90, 80, 70, 60, 10, 2, 3]

In [59]:
list1.insert(2,True)

In [60]:
list1

[2, 90, True, 80, 70, 60, 10, 2, 3]

In [64]:
list1.count(4)

0

In [66]:
list1.remove(90)

In [67]:
list1

[2, True, 80, 70, 60, 10, 2, 3]

In [68]:
list1.remove(2)

In [69]:

list1

[True, 80, 70, 60, 10, 2, 3]

In [70]:
list1.reverse()

In [71]:
list1

[3, 2, 10, 60, 70, 80, True]

In [72]:
list1.sort()

In [73]:
list1

[True, 2, 3, 10, 60, 70, 80]

In [78]:
list1.index(80)

6

In [80]:
list2=['yellow','green','blue']


In [81]:
list2.remove('green')
list2

['yellow', 'blue']

In [85]:
list2.extend(['pink','black'])

In [86]:
list2

['yellow', 'blue', ['pink', 'black'], 'pink', 'black']

In [87]:
list2[1:3]

['blue', ['pink', 'black']]

In [88]:
list2[:]

['yellow', 'blue', ['pink', 'black'], 'pink', 'black']

In [89]:
tupl=(1,2,3,True,'farooq')

In [90]:
tupl

(1, 2, 3, True, 'farooq')

In [91]:
tupl.count(1)

2

In [92]:
tupl.index(1)

0

In [93]:
dic={
    'one':'farooq',
     'two':'khan'
}

In [94]:
dic

{'one': 'farooq', 'two': 'khan'}

In [95]:
dic['one']

'farooq'

In [96]:
dic['two']

'khan'

In [97]:
so={}

In [98]:
so['one']='faoo'

In [99]:
so

{'one': 'faoo'}

In [100]:
so['two']=4

In [101]:
so

{'one': 'faoo', 'two': 4}

In [102]:
set1={1,1,2,3,4}

In [103]:
set1

{1, 2, 3, 4}

In [104]:
set2={1,3,5,6}

In [105]:
set1.difference(set2)

{2, 4}

In [106]:
set1.union(set2)

{1, 2, 3, 4, 5, 6}

In [107]:
set1. union(set2)

{1, 2, 3, 4, 5, 6}

In [108]:
name="farooqkhan"

In [109]:
name[0]

'f'

In [111]:
len(name)

10

In [112]:
name.isdigit()

False

name.lower(

In [113]:
name.upper()

'FAROOQKHAN'

In [114]:
import numpy as np

# numpy is a python  library .we are gonna understand what exactly it's mean
- like we know how exactly to code like function condiotion and loops
- we can write our own code
- sometime we need a huge efficient number manipulation 
- there we will use numpy library
- instead of writing our own code we will use something else who could do all these probelm for us
- it is code which is written by some else

In [123]:
x=np.arange(100,130,3)

In [124]:
x

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127])

In [125]:
x/10

array([10. , 10.3, 10.6, 10.9, 11.2, 11.5, 11.8, 12.1, 12.4, 12.7])

In [127]:
type(np)

module

In [131]:
x=np.array([1,2,3,4,5,6,'FAR'])

In [132]:
x

array(['1', '2', '3', '4', '5', '6', 'FAR'], dtype='<U11')

In [133]:
type(x)

numpy.ndarray

# homogenious datatype
- it's mean we should enter only the same exact data types

In [134]:
x.dtype

dtype('<U11')

In [135]:
arr1=np.array([1,2,3,4])

In [136]:
arr1

array([1, 2, 3, 4])

In [137]:
arr1.dtype

dtype('int32')

In [138]:
x.size

7

In [139]:
arr1.size

4

In [140]:
b=np.arange(0,44,2)

In [141]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42])

In [142]:
len(b)

22

In [143]:
b.size

22

In [144]:
type(b)

numpy.ndarray

In [145]:
b.dtype

dtype('int32')

In [146]:
bb=np.array(b)

In [147]:
bb

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42])

In [148]:
a=np.array([1,2,3,4,5,6])

In [149]:
a

array([1, 2, 3, 4, 5, 6])

In [154]:
a=np.array([[[1,2,3],[2,3,4]]])

In [155]:
a.ndim

3

In [156]:
a=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])

In [157]:
a.ndim

3

In [158]:
a=np.array([[[[2]],[[2]]],[[[3]],[[4]]],[[[5]],[[4]]],[[[5]],[[6]]]])

In [159]:
a.ndim

4

In [160]:
a=np.array([[[[4]]]])

In [161]:
a.ndim

4