In [1]:
!pip install tensorflow
!pip install keras 

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt


In [18]:
# inputs
inputs=tf.constant([[1,35]],'float32')

In [19]:
inputs

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1., 35.]], dtype=float32)>

In [20]:
# weigths
weights=tf.Variable([[-0.05],[-0.01]])

In [21]:
weights

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.05],
       [-0.01]], dtype=float32)>

In [22]:
# bias
bias=tf.Variable([0.5])

In [23]:
bias

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.5], dtype=float32)>

In [24]:
products=tf.matmul(inputs,weights)

In [25]:
products

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.4]], dtype=float32)>

In [26]:
dense=tf.keras.activations.sigmoid(products+bias)

In [27]:
dense

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5249792]], dtype=float32)>