In [1]:
!pip install tensorflow

In [64]:
!pip install keras

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
from scipy import stats
from scipy.optimize import minimize

In [3]:
tf

<module 'tensorflow' from 'C:\\Users\\SA\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py'>

In [4]:
type(tf)

module

In [5]:
d0=tf.ones((1,))

In [6]:
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [7]:
d1=tf.ones((1))

In [8]:
d1

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [9]:
d1.shape

TensorShape([1])

In [10]:
d1.ndim

1

In [11]:
d2=tf.ones((3,3,4 ))

In [12]:
d2

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [13]:
d2.shape

TensorShape([3, 3, 4])

In [14]:
d2.ndim

3

In [15]:
print(d2.numpy())

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [16]:
d3=tf.ones((5,2,6))

In [17]:
d3

<tf.Tensor: shape=(5, 2, 6), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]], dtype=float32)>

# define constant

In [18]:
from tensorflow import constant

In [19]:
a=constant(2,shape=[2,3])

In [20]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2]])>

In [21]:
a.ndim

2

In [22]:
a.shape

TensorShape([2, 3])

In [23]:
b=tf.constant(5,shape=[4,4])

In [24]:
b

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])>

In [25]:
b.numpy()

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [26]:
c=constant([1,2,3,4],shape=[2,2])

In [27]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [28]:
c.numpy()

array([[1, 2],
       [3, 4]])

In [29]:
tf.zeros((3,4,3))

<tf.Tensor: shape=(3, 4, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [30]:
a=tf.zeros_like((2,2,3))

In [31]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [32]:

print(a.numpy())

[0 0 0]


In [33]:
tf.fill([5,8],4)

<tf.Tensor: shape=(5, 8), dtype=int32, numpy=
array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])>

# define variable

In [34]:

a=tf.Variable([1,2,3,4],dtype=tf.float32)

In [35]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [36]:
a.numpy()

array([1., 2., 3., 4.], dtype=float32)

In [37]:
b=tf.constant(2,tf.float32)

In [38]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [39]:
a*b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 4., 6., 8.], dtype=float32)>

In [40]:
tf.multiply(a,b)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 4., 6., 8.], dtype=float32)>

In [41]:
from tensorflow import constant,add

In [42]:
A=constant([2])
b=constant([3])

In [43]:
A

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>

In [44]:
b

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [45]:
c=constant([[2,3],[4,4]])

In [46]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 4]])>

In [47]:
c.numpy()

array([[2, 3],
       [4, 4]])

In [48]:
c=constant([[[2,3,4],[3,3,5]],[[3,4,5],[2,3,4]]])

In [49]:
c

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[2, 3, 4],
        [3, 3, 5]],

       [[3, 4, 5],
        [2, 3, 4]]])>

In [50]:

c.ndim

3

In [51]:
add(A,b)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>

In [52]:
d=constant([[[2,3,4],[3,3,5]],[[3,4,5],[2,3,4]]])

In [53]:
tf.multiply(c,d)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 4,  9, 16],
        [ 9,  9, 25]],

       [[ 9, 16, 25],
        [ 4,  9, 16]]])>

In [54]:
gray=tf.random.uniform([2,2],maxval=255,dtype='int32')

In [55]:
gray

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[247, 149],
       [ 93, 199]])>

In [56]:
gray=tf.reshape(gray,[2*2,1])

In [57]:
gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[247],
       [149],
       [ 93],
       [199]])>

In [58]:
color=tf.random.uniform([3,2,3],maxval=255,dtype='int32')

In [59]:
color

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[194, 145,  11],
        [243, 163, 212]],

       [[253, 177,  39],
        [ 51,  66, 185]],

       [[111, 185,  63],
        [176, 204, 242]]])>

In [60]:
color=tf.reshape(color,[3*2,3])

In [61]:
color

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[194, 145,  11],
       [243, 163, 212],
       [253, 177,  39],
       [ 51,  66, 185],
       [111, 185,  63],
       [176, 204, 242]])>

# common loss function

In [69]:
tf.keras.losses

<module 'keras.api._v2.keras.losses' from 'C:\\Users\\SA\\anaconda3\\lib\\site-packages\\keras\\api\\_v2\\keras\\losses\\__init__.py'>

In [75]:
tf.keras.losses

<module 'keras.api._v2.keras.losses' from 'C:\\Users\\SA\\anaconda3\\lib\\site-packages\\keras\\api\\_v2\\keras\\losses\\__init__.py'>

In [77]:
target=10
prediction=5

In [79]:
loss=tf.keras.losses.mse(target,prediction)

InvalidArgumentError: Invalid reduction dimension (-1 for input with 0 dimension(s) [Op:Mean]